name = "Lady Ann's Trashcan"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa9dfdd82671a468aa9136ceff47ad41892176625105352d8715cfc920a9e6f2"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
