name = "Lady Ann's Trashcan"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df4a685e76cc68e8e1b9a5d1dfa5c72618e73f401dcfe21df98c8b609ce8fd3d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
