name = "Lady Ann's Trashcan"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5747f128996e78345f8a18aff0e471ea6d293a4f523e755d26a7d341c36be409"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
